services:
  - type: web
    name: sania-token-server
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: hypercorn app:app --bind 0.0.0.0:$PORT

    envVars:
      - key: LIVEKIT_URL
        sync: false

      - key: LIVEKIT_API_KEY
        sync: false

      - key: LIVEKIT_API_SECRET
        sync: false

      - key: LIVEKIT_AGENT_NAME
        value: aarna-sania-laptop-test

      - key: LIVEKIT_TOKEN_TTL_MINUTES
        value: "30"
